version: '3.7'

services:
  es-monitor:
    build: .
    image: es-monitor:0.6
    container_name: es-monitor
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./:/es-monitor
